theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/aubrey-beardsley-tree.jpg'
    footer: ''
  home:
    head:
      title: site
  breadcrumb:
    position: none
  projects:
    index:
      layout: grid
      options:
        categories: false
        image: true
        subtitle: false
        summary: true
        year: false
      truncate_description: 0
    share_links:
      enabled: false