theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/aubrey-beardsley-tree.jpg'
    footer: ''
  home:
    head:
      title: site
  breadcrumb:
    position: after-hero
  projects:
    index:
      layout: grid
      options:
        categories: false
        image: true
        subtitle: false
        summary: true
        year: false
      truncate_description: 0
    share_links:
      enabled: false
  seo:
    title:
      separator: "×"
  default:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: false
    single:
      taxonomies:
        position: hero
        show_name: false